### PR TITLE
Fix Django 4.0 compatibility (fixes #384)

### LINKED ISSUE #384: Django 4.0 compatibility issue
Seeing following import issue when trying to run w/ Django 4.0:

```
 File "/.../venv39/lib/python3.9/site-packages/post_office/admin.py", line 7, in <module>
    from django.conf.urls import re_path
ImportError: cannot import name 're_path' from 'django.conf.urls' (/.../venv39/lib/python3.9/site-packages/django/conf/urls/__init__.py)
```

### PR DESCRIPTION
**Pull request by Uninen**
Fixes #384 

- changed `re_path` import from `django.conf.urls` to `django.urls`
- replaced `force_text` with `force_str`

The tests are not using GH actions so didn't touch those.

### CODE REVIEW

**Comment by jrief** [comment]
Thank @Uninen for this pull request, but without also adopting the unit tests to run with Django-4.0, I won't merge it.

**Comment by selwin** [comment]
So the files that need to be updated are:
https://github.com/ui/django-post_office/blob/master/tox.ini
https://github.com/ui/django-post_office/blob/master/.travis.yml

Django 4.0 should be tested on Python >= 3.8

**Review by domdinicola — APPROVED** [review]

**Comment by domdinicola** [comment]
https://github.com/ui/django-post_office/pull/389

**Comment by selwin** [comment]
Fixed in https://github.com/ui/django-post_office/pull/389

**Pull request closed without merging**
