### PR TITLE
Set the default autofield for the app Fixes: #391 #377

### LINKED ISSUE #377: DEFAULT_AUTO_FIELD Warnings in django 3+
please set up the auto field to remove warnings

`HINT: Configure the DEFAULT_AUTO_FIELD setting or the PostOfficeConfig.default_auto_field attribute to point to a subclass of AutoField, e.g. 'django.db.models.BigAutoField'.`

Thank you

### LINKED ISSUE #391: Running `makemigrations --check --dry-run` fails because of missing migration file.
Running the command `django-admin makemigrations --check --dry-run` results with exit code `1`, because the project is missing a migration file.

### PR DESCRIPTION
**Pull request by CirXe0N**
closes #391, closes #377

### CODE REVIEW

**Comment by alexandernst** [comment]
This is required because of [this Django change](https://docs.djangoproject.com/en/3.2/releases/3.2/#customizing-type-of-auto-created-primary-keys)

**Comment by selwin** [comment]
Actually, I'd want to eventually use Django's default `BigAutoField` (less surprise for large scale email senders). Should we just open a migration to migrate to `BigAutoField`?

**Comment by selwin** [comment]
Thanks!

**Comment by alexandernst** [comment]
@selwin my pleasure! Can we get a minor release containing this?

**Pull request merged**
