### PR TITLE
Fix: use bleach 5.0.0 css sanitizer

### PR DESCRIPTION
**Pull request by franciscobmacedo**
bleach 5.0.0 `clean` method should include `css_sanitizer`.

### CODE REVIEW

**Comment by fasih** [comment]
I think we need to add additional dependencies `bleach[css]` in the `setup.py` file as well

`install_requires=['django>=2.2', 'jsonfield>=3.0', 'bleach', 'pytz', 'bleach[css]']`

**Comment by franciscobmacedo** [comment]
> Is this PR backward compatible with bleach <5.0? @franciscobmacedo

I guess it doesn't, should i require `bleach>=5.0` in the `install_requires`?

**Comment by selwin** [comment]
Can you slightly modify this PR to fallback to the old behavior on bleach < 5? I prefer to not pin dependencies when I can. If we force people to upgrade, this may also affect code in their own projects.

**Comment by franciscobmacedo** [comment]
sure, will do

**Comment by selwin** [comment]
@franciscobmacedo do you mind resolving the conflicts on `setup.py`?

**Comment by franciscobmacedo** [comment]
I'm sorry for the delay, I haven't been that active here recently.

**Comment by selwin** [comment]
Thanks!

**Comment by domdinicola** [comment]
is this going to be released soon?

**Comment by franciscobmacedo** [comment]
I think it is released in [3.6.1](https://github.com/ui/django-post_office/releases/tag/v3.6.1)

**Comment by domdinicola** [comment]
I think the package does not include the templates...

**Pull request merged**
