### PR TITLE
Replace jsonfield with jsonfield2

### LINKED ISSUE #284: External dependency is no longer supported
Incompatible with newer versions of the Django.
Problem with jsonfield
There is some ways to resolve problem.
Separeted from #274 
https://github.com/ui/django-post_office/issues/274#issuecomment-561696438

### PR DESCRIPTION
**Pull request by Mogost**
Fix #284

### CODE REVIEW

**Comment by Mogost** [comment]
@selwin I decided to replace the unsupported library with a fork. This is probably the safest way.

@rpkilby Our build failed only with the latest **jsonfield2** (**3.1.0** version). With **3.0.3** build is successful.
Could you check why the build with the latest version is unsuccessful?
It would also be great to receive from you a confirmation of the intention to continue supporting jsonfield2.
Also, if possible, tell us how safe the transition from **jsonfield** to **jsonfield2** is for us.

**Comment by Mogost** [comment]
I think the build failed due to https://github.com/rpkilby/jsonfield2/issues/20

**Comment by Mogost** [comment]
Oh, sorry. 
Missed in ChangeLog
> Drop Django 2.1 (and below) support
@selwin What do you think about ending support Django 1.11?

**Comment by Mogost** [comment]
Also @jrief what do you think we should do?

**Comment by rpkilby** [comment]
Also, per the 3.0 [release notes](https://docs.djangoproject.com/en/3.0/releases/3.0/#third-party-library-support-for-older-version-of-django), they recommend 3rd party apps to drop support for Django 2.1 and below.

> Also, if possible, tell us how safe the transition from jsonfield to jsonfield2 is for us.

It should be a simple drop-in replacement. Testing locally, I didn't run into any data issues moving from jsonfield to jsonfield2. Make sure that you uninstall jsonfield before installing jsonfield2, since they share the same module paths, and uninstalling jsonfield after the fact will remove modules owned by jsonfield2.

**Comment by Mogost** [comment]
Also, I made a request to transfer access from an unsupported jsonfield to the owner of jsonfield2.
https://github.com/rpkilby/jsonfield2/issues/24
The original owner has replied.
I think we can expect new releases to appear on jsonfield.

**Comment by selwin** [comment]
👍🏻

**Comment by blorenz** [comment]
Here we sit, with no movement on `jsonfield`. Is there an alternative action that can be taken?

**Comment by selwin** [comment]
We can go with `jsonfield2` for the next release. I just want to confirm with @Mogost that the forked library is fully backwards compatible with `jsonfield`. There's no migration step that needs to be done, right?

**Comment by Mogost** [comment]
@selwin No migration step needed.
In the last commit, I froze jsonfield2 on a last compat with Django 1.11 version.
As we see the tests passed.
I think after the official EOL Django==1.11.* we will remove the freeze

**Comment by selwin** [comment]
Ok, let's go with jsonfield2 then. Additionally, I'm ok with supporting django >= 2.0 because keeping compatibility across Django 1.x all the way to 3.x is more trouble than it's worth.

**Comment by Mogost** [comment]
> Ok, let's go with jsonfield2 then. Additionally, I'm ok with supporting django >= 2.0 because keeping compatibility across Django 1.x all the way to 3.x is more trouble than it's worth.

I propose to keep 1.11 until the official EOL which is in April.
By April I will prepare a more meaningful PR which drop support olds django.

**Comment by selwin** [comment]
How about we merge that PR in and release the next version in April? After that gets merged in, we also have to do some code maintenance like removing compatibility codes and decide when to launch it.

I'm actually not too worried about dropping Django 1.11 support because Django themselves recommend it this time around. https://docs.djangoproject.com/en/3.0/releases/3.0/#third-party-library-support-for-older-version-of-django

**Comment by Mogost** [comment]
I would suggest merging this PR now and releasing a new version now too.
All tests that are in the project were successful with all versions of django from 1.11 to django-master.

**Comment by Mogost** [comment]
@selwin Please merge that.

**Comment by Mogost** [comment]
@selwin Thanks! New release is also expected.

**Comment by rpkilby** [comment]
Hi all. I've recently been given ownership of `jsonfield` and have merged `jsonfield2`'s changes back in. `jsonfield` v3.0 is up on PyPI, which is Python 3 and Django 2.2/3.0-compatible.

**Comment by kakulukia** [comment]
I saw the last update and wanted to try it out .. :/ 

File ".../site-packages/post_office/settings.py", line 105, in <module>
    context_field_class = import_string(CONTEXT_FIELD_CLASS)
  File ".../site-packages/django/utils/module_loading.py", line 22, in import_string
    raise ImportError('Module "%s" does not define a "%s" attribute/class' % (
ImportError: Module "jsonfield" does not define a "JSONField" attribute/class

```
django-post-office 3.3.0 
jsonfield2         3.0.3
```

**Comment by rpkilby** [comment]
Hi @kakulukia. Try reinstalling jsonfield2 in your environment. It sounds like you're running into the same issue as https://github.com/dj-stripe/dj-stripe/pull/1023

**Comment by kakulukia** [comment]
Thanks! This worked and should be a general warning for anyone trying to upgrade.

**Comment by rpkilby** [comment]
Fortunately, this should no longer be an issue as projects can now go back to using `jsonfield`.

**Pull request merged**
