### PR TITLE
also rename translated templates together with its parent

### PR DESCRIPTION
**Pull request by kakulukia**
added date hierarchy for emails to better find what you are looking for
searchable recipient and subject 
translated templates are ordered by language 
templates are ordered by name 
pep8 fixes to make the IDE and the developer heart happy
if the name got changed, also change the translated templates to match again

### CODE REVIEW

**Comment by selwin** [comment]
I just merged in a PR that added compatibility for Django 2.0 and the merge broke this PR. Could you please resolve the conflicts so I can merge this in for the next release? Sorry about that.

**Comment by kakulukia** [comment]
done @selwin

**Comment by kakulukia** [comment]
passed .. go ahead!

**Comment by selwin** [comment]
Sorry for the wait, thanks!

**Comment by kakulukia** [comment]
awesome!

**Pull request merged**
