### PR TITLE
Migrations, translations, bugs...

### PR DESCRIPTION
**Pull request by fizista**
So...

I cleaned a little code, fixed a few bugs and added translation. I've also added the ability to run tests using TOX.

All tests run for Django from version 1.4 to 1.9, and Python versions 2.6 to 3.5.

1) Removed language choices from the model EmailTemplate.
Fixes a bug missing migration. There was a problem with the configuration parameter LANGUAGES.
2) Added missing South migrations.
3) Updated gitignore.
4) The new translation into Polish
5) Add TOX
Added testing environment similar to Travis. Tests can be run at home.
https://pypi.python.org/pypi/tox
6) FIX: DeprecationWarning: Please use assertEqual instead.

### CODE REVIEW

**Comment by selwin** [comment]
Thanks for the PR @fizista. I believe the dynamic languages setting problem has been fixed in https://github.com/ui/django-post_office/pull/153 . Do you mind opening a separate PR for the assertEqual deprecation warning fixes?

**Comment by fizista** [comment]
No! That patch(#153) does not work. Look at the screenshots.

My patch:
patch_django_postoffice_my_158

Patch #153:
patch_django_postoffice_153

My solution works. So you may need to remove a patch #153, and put all my code?

Send me what you think. I can adapt the code or divide it.

**Comment by selwin** [comment]
@fizista sorry for the late reply. Alright, I think having the languages be a dropdown choice is definitely better, I didn't check how the admin interface look like on the other PR.

Could you please delete the migration files and generate a new one? This way we'll have only one migration file instead of two.

**Comment by fizista** [comment]
Finished. Everything should work.

**Comment by selwin** [comment]
I have reverted the previous migration related PR in https://github.com/ui/django-post_office/pull/163 . Could you please resolve the merge conflicts so I can merge this in?

**Comment by fizista** [comment]
Finished.

**Comment by selwin** [comment]
Thanks!

**Pull request merged**
