### PR TITLE
Update __init__.py

### PR DESCRIPTION
**Pull request by codertjay**
I realized most time the images are not been attached and it has been giving error

### CODE REVIEW

**Comment by codertjay** [comment]
I realized most time the images are not been attached and it has been giving error

**Comment by selwin** [comment]
Sorry, I'm not sure what error this PR fixes. Can you provide more details?

**Comment by codertjay** [comment]
Nothing much but it can’t be used without add files or image’s

**Comment by codertjay** [comment]
Fon

**Pull request merged**
