### PR TITLE
Fixes for Django 2.0

### PR DESCRIPTION
**Pull request by PetrDlouhy**

### CODE REVIEW

**Comment by PetrDlouhy** [comment]
@ui Django 2.0 is released now. I have updated this to use official 2.0 version in Travis. Can You please merge this and make PIP package?

**Comment by Mogost** [comment]
I vote for that!
@selwin can you merge this and make new release?

**Comment by selwin** [comment]
Fixed in https://github.com/ui/django-post_office/pull/217

**Comment by selwin** [comment]
Version 3.0.4 is now up on PyPI.

**Pull request closed without merging**
